name: securechat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  encrypt: ^5.0.3
  crypto: ^3.0.6
  http: ^1.2.2
  intl: ^0.20.1
  flutter_contacts: ^1.1.9+2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  flutter_sms: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
